import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  listContainer: {
    paddingBottom: 80,
    paddingTop: 10,
  },
  animatedHeader: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    marginBottom: 10,
  },
  animatedEmoji: {
    fontSize: 88,
    marginBottom: 8,
    opacity: 0.5
  },
  animatedText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C2C2C',
    textAlign: 'center',
    marginBottom: 15,
  },
  separator: {
    width: 50,
    height: 2,
    backgroundColor: '#16e00fff',
    borderRadius: 1,
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F5F5F5',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    height: 150,
    padding:5
  },
  productImageContainer: {
    width: 106,
    height: 'auto',
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: 12,
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  addButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#5ac727ff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#D4AF37',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  productInfo: {
    flex: 1,
    justifyContent: 'space-between',
    height: '100%',
  },
  productName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2C2C2C',
    marginBottom: 2,
    letterSpacing: 0.2,
  },
  restaurantName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#D4AF37',
    marginBottom: 2,
  },
  productDescription: {
    fontSize: 12,
    color: '#7A7A7A',
    lineHeight: 16,
    marginBottom: 10,
  },
  productFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  currency: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C2C2C',
  },
  price: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2C2C2C',
    marginLeft: 1,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffffff',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 0.4,
    borderColor: '#e2d02dff',
  },
  rating: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D4AF37',
    marginRight: 4,
  },
  distance: {
    fontSize: 10,
    color: '#7A7A7A',
    fontWeight: '500',
    marginLeft: 7,
  },
  itemSeparator: {
    height: 4,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
    paddingHorizontal: 40,
  },
  emptyStateText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#7A7A7A',
    textAlign: 'center',
    marginBottom: 8,
  },
  emptyStateSubtext: {
    fontSize: 16,
    color: '#B0B0B0',
    textAlign: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 18,
    color: '#7A7A7A',
    marginTop: 16,
    fontWeight: '600',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  errorText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#666666',
    textAlign: 'center',
    marginBottom: 8,
  },
  errorSubtext: {
    fontSize: 16,
    color: '#7A7A7A',
    textAlign: 'center',
  },
});