// src/utils/imageMap.ts
// Centralized static image map for local assets

const imageMap: { [key: string]: any } = {
  'coffee.jpg': require('../assets/coffee.jpg'),
  'coffee2.jpg': require('../assets/coffee2.jpg'),
  'coffee4.jpg': require('../assets/coffee4.jpg'),
  'coffee5.jpg': require('../assets/coffee5.jpg'),
  'cold_coffee.jpg': require('../assets/cold_coffee.jpg'),
  'Cookie.jpg': require('../assets/Cookie.jpg'),
  'dessert2.jpg': require('../assets/dessert2.jpg'),
  'Masala_Chai.jpg': require('../assets/Masala_Chai.jpg'),
  'pastry.jpg': require('../assets/pastry.jpg'),
  'Profile.png': require('../assets/Profile.png'),
  'restaurant1.jpg': require('../assets/restaurant1.jpg'),
  'roll1.jpg': require('../assets/roll1.jpg'),
  'showcase.png': require('../assets/showcase.png'),
  'snack2.jpg': require('../assets/snack2.jpg'),
  'tea.jpg': require('../assets/tea.jpg'),
  'tea4.jpg': require('../assets/tea4.jpg'),
  'brownie.jpg': require('../assets/brownie.jpg'),
  'chaat1.jpg': require('../assets/chaat1.jpg'),
  'chaat2.jpg': require('../assets/chaat2.jpg'),
  'coffee1.jpg': require('../assets/coffee1.jpg'),
  'coffee3.jpg': require('../assets/coffee3.jpg'),
  'coffee6.jpg': require('../assets/coffee6.jpg'),
  'coffee7.jpg': require('../assets/coffee7.jpg'),
  'dessert1.jpg': require('../assets/dessert1.jpg'),
  'restaurant2.jpg': require('../assets/restaurant2.jpg'),
  'restaurant3.jpg': require('../assets/restaurant3.jpg'),
  'restaurant4.jpg': require('../assets/restaurant4.jpg'),
  'roll.jpg': require('../assets/roll.jpg'),
  'snack1.jpg': require('../assets/snack1.jpg'),
  'tea2.jpg': require('../assets/tea2.jpg'),
  'tea3.jpg': require('../assets/tea3.jpg'),
  'tea5.jpg': require('../assets/tea5.jpg'),
  'tea6.jpg': require('../assets/tea6.jpg'),
  'tea7.jpg': require('../assets/tea7.jpg'),
  'tea8.jpg': require('../assets/tea8.jpg'),
  'lemon_tea.jpg': require('../assets/lemon_tea.jpg'),
};

export default imageMap;
